# data_demo = {
#     'orders_id': '1',
#     'client_customers_id': '1',
#     'customers_telephone': '9726441011',
#     'customers_email': None,
#     'shipping_method': None,
#     'tracking_number': None,
#     'ref_number': '',
#     'order_number': None,
#     'delivery_name': 'John Nguyen',
#     'delivery_state': 'TX',
#     'delivery_country': 'United States',
#     'delivery_company': '',
#     'delivery_suburb': '',
#     'delivery_city': 'Richardson',
#     'delivery_address2': None,
#     'delivery_address1': '',
#     'delivery_postcode': '75081',
#     'billing_suburb': '',
#     'billing_company': '',
#     'billing_city': 'Richardson',
#     'billing_country': 'United States',
#     'billing_state': 'TX',
#     'billing_address2': None,
#     'billing_name': 'John Nguyen',
#     'billing_address1': '',
#     'billing_postcode': '75081',
#     'payment_method': 'Cash on Delivery',
#     'cc_type': '',
#     'cc_owner': '',
#     'cc_number': '',
#     'cc_expires': '',
#     'last_modified': None,
#     'date_purchased': '2007-05-18 11:46:26',
#     'orders_status': '1',
#     'orders_date_finished': None,
#     'currency': 'USD',
#     'currency_value': '1.000000',
#     'client_navision_id': None,
#     'client_orders_id': None,
#     'order_total': None,
#     'orders_products_id': '1',
#     'products_name': 'ALRI: Regeneration X Watermelon Margarita',
#     'products_price': '0.0000',
#     'final_price': '0.0000',
#     'products_tax': '0.0000',
#     'products_quantity': '1',
#     'products_lsfs_item_id': None,
#     'products_upc_code': '',
#     'orders_total_id': '1',
#     'title': 'Sub-Total:',
#     'text': '$0.00',
#     'value': '0.0000',
#     'class': 'ot_subtotal',
#     'sort_order': '1',
#     'customers_id': '1',
#     'customers_gender': 'm',
#     'customers_firstname': 'John',
#     'customers_lastname': 'Nguyen',
#     'customers_dob': '1975-09-10 00:00:00',
#     'customers_email_address': 'john@lsfulfillment.com',
#     'customers_default_address_id': '1',
#     'customers_fax': '',
#     'customers_password': '2e7687bfd53846bcd73be75eef88e07a:74',
#     'customers_newsletter': '0',
#     'customers_info_id': '1',
#     'customers_info_date_of_last_logon': '2008-07-27 21:34:49',
#     'customers_info_number_of_logons': '21',
#     'customers_info_date_account_created': '2007-05-18 11:37:08',
#     'customers_info_date_account_last_modified': '2007-08-22 14:29:57',
#     'global_product_notifications': '0',
#     'address_book_id': '1',
#     'entry_gender': 'm',
#     'entry_company': '',
#     'entry_firstname': 'John',
#     'entry_lastname': 'Nguyen',
#     'entry_street_address': '1110 E. Collins Blvd. Ste. 122',
#     'entry_suburb': '',
#     'entry_postcode': '75081',
#     'entry_city': 'Richardson',
#     'entry_state': '',
#     'entry_country_id': '223',
#     'entry_zone_id': '57'
# }

temp_address = {
    'id': 'address_book_id',
    'code': 'entry_postcode',
    'first_name': 'entry_firstname',
    'last_name': 'entry_lastname',
    'address_1': 'entry_street_address',
    'address_2': '%s/%s' % ('entry_city', 'entry_state'),
    'city': 'entry_city',
    'country': {
        'id': 'countries_id',
        'code': '%s/%s' % ('countries_iso_code_2', 'countries_iso_code_3'),
        'country_code': 'countries_iso_code_2',
        'name': 'countries_name',
    },
    'state': {
        'id': 'zone_id',
        'code': 'zone_country_id',
        'state_code': 'zone_code',
        'name': 'zone_name',
    },
    'postcode': 'entry_postcode',
    'telephone': 'customers_telephone',
    'company': 'entry_company',
    'fax': 'customers_fax',
}

customer_address = {
    'gender': 'entry_gender',
    'default': {
        'billing': True,
        'shipping': True,
    },
    'billing': True,
    'shipping': True,
    'created_at': 'customers_info_date_account_created',
}

r = temp_address
r.update(customer_address)
print(r)
